services:
  customers:
    image: donnatto/customers:0.0.1-SNAPSHOT
    platform: linux/amd64
    ports:
      - 9001:9001
    networks:
      - spring
      - mysqlspring
      - kafka-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/donnatto
      - spring.kafka.bootstrap-servers=http://kafka:9092
    depends_on:
      - mysqldb
      - kafka
        
  transactions:
    image: donnatto/transactions:0.0.1-SNAPSHOT
    platform: linux/amd64
    ports:
      - 9002:9002
    networks:
      - spring
      - mysqlspring
      - kafka-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/donnatto
      - spring.kafka.bootstrap-servers=http://kafka:9092
    depends_on:
      - mysqldb
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTERN_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  mysqldb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3306:3306
    networks:
      - mysqlspring
    environment:
      MYSQL_DATABASE: donnatto
      MYSQL_USER: donnatto
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
      
networks:
  spring:
    driver: bridge
  mysqlspring:
    driver: bridge
  kafka-net:
    driver: bridge
